### ISSUE TITLE
Component not update when setting the binding value

### ISSUE THREAD

**Issue by hevilhuy** [tinymce/tinymce-blazor#11]
`<Editor ApiKey="@Configuration["TinyMCEApiKey"]" @bind-Value="@FormModel.Content" Conf="TinyMCEConfigurations.NormalEditorConfigurations"/>`

```
private void ResetForm()
{
     FormModel = new();
}
```

When calling ResetForm the content of the component wont reset.

**Comment by jscasca** [comment]
I'll have to investigate what is going on here. Thanks for bringing this up.

**Comment by jscasca** [comment]
Ok I think I have found the issue. It was due to a null reference going unchecked. I will have this sorted out in #12

**Comment by jscasca** [comment]
@hevilhuy this should be fixed in v0.0.4 which has just been released

**Comment by hevilhuy** [comment]
> 
> 
> @hevilhuy this should be fixed in v0.0.4 which has just been released

Thank you.
