### ISSUE TITLE
Version 5 causes error that version 3 does not have.

### ISSUE THREAD

**Issue by hevilhuy** [tinymce/tinymce-blazor#15]
This error on occur in version 5. I tried to rollback to version 3 and everything is OK.
![image](https://user-images.githubusercontent.com/17383256/118237924-0118f500-b4c2-11eb-8afc-1559f7ef93df.png)

**Comment by jscasca** [comment]
I haven't seen this before so my best guess is that it is related to how the element is being disposed.

When in the element life-cycle is the error appearing?
Do you have a small replication case that we can use to better understand the situation? Maybe a small github project?

**Comment by hevilhuy** [comment]
I can share my live share to you. Do you use Discord?

**Comment by hevilhuy** [comment]
![image](https://user-images.githubusercontent.com/17383256/118347079-9a9be180-b56a-11eb-93ff-2b269f60c254.png)

**Comment by jscasca** [comment]
Yeah, unfortunately, I only have a Mac available at the time and Visual Studio Mac doesn't support liveshare.

But the first error is definitely an issue with disposing of the element. The second screenshot looks like JS is trying to call the c# code and fails, so maybe is trying to reach out to it with the outdated reference?

Let me dig a bit more into it.

**Comment by hevilhuy** [comment]
Please add me on Discord and we will discuss this. 
My Discord is Red Wei#2396

**Comment by nguyenhthai** [comment]
Just recently encountered this issue as well. I believe this happened when there are 2 or more instances of tinymce in the page.

**Comment by hevilhuy** [comment]
> Just recently encountered this issue as well. I believe this happened when there are 2 or more instances of tinymce in the page. I did some digging with at least 2 instance of tinymce.
> 
> During the dispose process, **destroy()** method is called and successfully removed the first instance. Then **destroy()** is called again and also successfully removed the second one. However, after this, **editor.on(blazorConf.modelEvents)** is triggered, which in turn calls the **update()** method. **update()** method does use **dotNetRef** which is already gone at that time.

Việt Nam điểm danh!

**Comment by jscasca** [comment]
Yeah, thanks to @hevilhuy I could work out a simple replication. Easiest way out is to just unbind all the events before disposing of the Editor to avoid that error

This should be fixed with #16
