### ISSUE TITLE
No way to import content.css

### ISSUE THREAD

**Issue by hevilhuy** [tinymce/tinymce-blazor#18]
I have 2 pages:
 - Read article
 - Write article

The write article page is using `<Editor>` tag and the read article page does not and the read article page cannot render the same as write article page.

In the write article page
![image](https://user-images.githubusercontent.com/17383256/119763544-ef7c1800-bed9-11eb-9a62-37227a521ef4.png)
In the read article page
![image](https://user-images.githubusercontent.com/17383256/119763569-fefb6100-bed9-11eb-8806-27d0346464d1.png)

**Comment by jscasca** [comment]
Hi @hevilhuy 

From the [code sample docs](https://www.tiny.cloud/docs/plugins/opensource/codesample/#usingprismjsonyourwebpage):

> You need to add prism.js and prism.css to your page in order to get the syntax highlighted code samples on your webpage (as created by the Code Sample plugin).
