### ISSUE TITLE
Self-Hosted / without Api key

### ISSUE THREAD

**Issue by drlee91** [tinymce/tinymce-blazor#20]
hey tinymce team,

my application(blazor server app) is hosted locally by the customers on their iis servers. is there any way to self host tinymce-blazor without api key? since registering the many domains is not possible and the applications mostly run offline in their intranet.

best regards

**Comment by jscasca** [comment]
Hi @drlee91 

I believe you can self-host without an api-key according to this question: https://github.com/tinymce/tinymce-docs/issues/1810

You can use the blazor wrapper with a self-hosted installation by pointing the `ScriptSrc` property of the wrapper to the location of your TinyMCE.

**Comment by drlee91** [comment]
Thanks a lot! :)
