### ISSUE TITLE
Rebuild editor not triggered on re-render

### ISSUE THREAD

**Issue by Cr3ature** [tinymce/tinymce-blazor#29]
Hi,

I have a setup where I have a list of sections. Each section is setup to bind there content to a editor component. 
When I add or remove a section. The editor values are changed, but the visible value in the editor is not. If I reference the editor, then the editor.Value is changed though.

Example reproduction steps:
- I have a array of sections with total count of 2. First one has 'Content 1', second one has 'Content 2'.  (Each render a new editor with those values filled)
- I add a section to the array. This triggers the render of a new editor which has value 'Content 3'.
- I remove the second item from the array with 'Content 2'. 
- The parent components trigger the re-render and the second is dropped from the screen. But the visible content of the editor still contains 'Content 2' and not 'Content 3' as should.

The value state has been updated all the way, but not in the editor.

Is it possible to trigger a rebuild of the component?

**Comment by jscasca** [comment]
Hey @Cr3ature any chance you can share a reproduction of this case? If you have a github repo or something similar I can take a better look into it. 

How are the values filled in for each editor? My guess is that is not triggering a setContent for the editor

**Comment by Cr3ature** [comment]
Hey @jscasca, I made a demo that reproduces my case.
https://github.com/Cr3ature/MudBlazor-TinyMce

Hope this helps,

Best regards

**Comment by Cr3ature** [comment]
Hey @jscasca, did you by any chance have found a solution or workaround for this case?

**Comment by jscasca** [comment]
@Cr3ature sorry it took this long, December is a crazy period. The simple workaround should be using the `@key` directive in your `TinyMceDemo` component. This should ensure that the current component gets the correct reference. E.G:
```
<TextEditorComponent @key="sectionDemo"  @bind-Value="sectionDemo.Content"... />
```
Let me know if this helps

**Comment by Cr3ature** [comment]
@jscasca  I know the feeling. The crazy period consists here. I tried adding the directive and it resolved my issue. Big thanks for looking into it. 

I learned an important directive that will be used a lot in future codebases.
