### ISSUE TITLE
How to insert HTML content at cursor point ?

### ISSUE THREAD

**Issue by alex241175** [tinymce/tinymce-blazor#35]
In javascript, we can insert content using command tinyMce.editor.execCommand('mceInsertContent', false, noteText);
How to do this in Blazor context?

**Comment by jscasca** [comment]
Hey @alex241175 unfortunately, the Blazor component currently doesn't have that implemented (yet). You would have to access the editor via the JS side of things to run that command.

Can you tell me more about your particular use case? We can probably expose a component function to insert the content if needed.

**Comment by jscasca** [comment]
I made #44 to address this. You should be able to have something like this: `<Editor @ref="MyEditor" />` and then call `MyEditor.insertContent("My content")`.

@kgbhun @alex241175 would this work for your current use cases?

**Comment by kgbhun** [comment]
Thanks, that would be great. In the meantime, I bridged it with a
javascript call, but it would be nice if it was built in originally

                        <Editor @ref="editor"

 ApiKey='1z643wn75msuvvneapfbakduywksxpc0eomneahqlt69lfp5'
                           Field="() => model.WorkflowContent"
                           @***@***.***"
                           ***@***.***"
                        />
    JSRuntime.InvokeVoidAsync("insertHTML",editor.Id,"something");
    <script>
     function insertHTML(id,html) {
getTiny().get(id).execCommand('mceInsertContent', false, html); }
    </script>

jscasca ***@***.***> ezt írta (időpont: 2022. ápr. 6., Sze,
7:39):

**Comment by jscasca** [comment]
This feature was added and it's available in our latest release v1.0.2
