### ISSUE TITLE
How to self host tinymce-blazor edition?

### ISSUE THREAD

**Issue by janissimsons** [tinymce/tinymce-blazor#36]
I want to self host TinyMCE and use it in my blazor application.
Is it possible to do it using this tinymce-blazor package?
Or does it work only with the cloud subscription?

**Comment by jscasca** [comment]
@janissimsons you can use self-hosted in your blazor application.  There are two ways of doing that:

You can load your own version of TinyMCE in your `_host.cshtml` file or your `index.html` file before loading the blazor server script `<script src="_framework/blazor.server.js"></script>`

Or you can use the property `ScriptSrc` to point to the location of your self-hosted `TinyMCE.min.js` file.

Let me know if this helps

**Comment by janissimsons** [comment]
Perfect, thank you.
