### ISSUE TITLE
How to edit with markdown

### ISSUE THREAD

**Issue by BeiYinZhiNian** [tinymce/tinymce-blazor#38]
Markdown is supported on the official website, but not in blazor. I don't know how to open it

**Comment by jscasca** [comment]
@BeiYinZhiNian you can achieve markdown behaviour by using the text pattern plugin as documented here: [text pattern plugin](https://www.tiny.cloud/docs/plugins/opensource/textpattern/). How are you passing the Blazor editor your configuration?

**Comment by BeiYinZhiNian** [comment]
Thanks, it works perfectly
