### ISSUE TITLE
Customize header text/Remove menu (only leave Toolbar)

### ISSUE THREAD

**Issue by zabronm** [tinymce/tinymce-blazor#4]
Hi guys thank you for the component

How do we archive the following:
1. Remove the menu bar and only leave Toolbar (with same functions as on the menu bar)?
2. Remove or customize the header text ("Here the editor")

Thank you.

**Comment by jscasca** [comment]
Hi @zabronm,

What version are you using? The 'Here...' thing shouldn't be in the [official package](https://www.nuget.org/packages/TinyMCE.Blazor/).

To remove the menu bar you can set the `menubar` property to false in the wrapper. For example:
```
<Tinymce.Blazor.Editor
  menubar=false
  toolbar=''<your_custom_toolbar_buttons>" />
```
To create the toolbar you want you might have to create your own dropdown menus. Here you can find a list of the default menu options: [Basic Setup](https://www.tiny.cloud/docs/general-configuration-guide/basic-setup/#defaultmenucontrols)

Let me know if this helps
