### ISSUE TITLE
TinyMCE 6 styleselect attribute does not work

### ISSUE THREAD

**Issue by BeiYinZhiNian** [tinymce/tinymce-blazor#40]
styleselect attribute

The same configuration works normally in 5 and is not displayed in 6. Does 6 need special configuration?

![image](https://user-images.githubusercontent.com/25119211/159439932-d6774049-2d29-453f-af4e-a56e06ed47ba.png)

![image](https://user-images.githubusercontent.com/25119211/159439498-fbbac076-efa2-45da-a4f3-f933b4194219.png)

**Comment by jscasca** [comment]
I believe that changed to `styles`. For changes regarding the editor and migrating to TinyMCE v6 feel free to visit the [editor repo](https://github.com/tinymce/tinymce). The Blazor wrapper supports both versions
