### ISSUE TITLE
Not working in Blazor Webassembly

### ISSUE THREAD

**Issue by kimermed** [tinymce/tinymce-blazor#42]
I don't see any instructions for using this component with Blazor Webassembly. When trying in a WA project I get this console error:

**Unhandled exception rendering component: Could not find 'tinymceBlazorWrapper.init' ('tinymceBlazorWrapper' was undefined).**

Do you have instructions for usage in Blazor Webassembly?

**Comment by jscasca** [comment]
@kimermed you just need to add the proper reference to the js library included with the component.

In your `wwwroot` folder you will find the `index.html` where you can reference the library. E.G.:
```
    <script src="_content/TinyMCE.Blazor/tinymce-blazor.js"></script>
    <script src="_framework/blazor.webassembly.js"></script>
```

Let me know if that helps

**Comment by kimermed** [comment]
I had those references but in reversed order. Swapping the order fixes it, thanks.
