### ISSUE TITLE
Toolbar popup does not disappear when navigating away or editor has been disposed

### ISSUE THREAD

**Issue by nguyenhthai** [tinymce/tinymce-blazor#43]
I ran into this issue recently and can replicate this with my repo [here](https://github.com/nguyenhthai/TinyMceBlazorToolbarIssue).

**Issue**: If toolbar is displayed and the editor either been disposed or we navigate away from the current component, the toolbar popup is still shown.

**Reproducible step**:

1. Click on the "More" icon to toggle toolbar
2. Either navigate to different page or click Destroy editor button to dispose the editor
3. The toolbar popup is still displayed

Some screenshots to show the issue
![image](https://user-images.githubusercontent.com/6546158/161818742-9f5d1d48-97ed-4e2a-ab88-d1fbc9c1a949.png)
![image](https://user-images.githubusercontent.com/6546158/161818809-95cc2e78-d2c5-4cdc-a7fe-112249201d40.png)

**Comment by jscasca** [comment]
@nguyenhthai Thanks for bringing that up. It seems that the order it disposes of the editor is breaking the popup and leaving it there. I'll get that fixed

**Comment by jscasca** [comment]
This has been addressed in our latest release, v1.0.2.

Let me know if you still have issues with it

**Comment by nguyenhthai** [comment]
@jscasca Unfortunately, the fix for this reverted the fix for #15. I have updated my repo to show the issues.

**Comment by jscasca** [comment]
@nguyenhthai I might have to do a better clean up job for multiple editors. Can you open a new tickets for this? 'Editor clean up not properly disposing of event handlers' maybe?

**Comment by nguyenhthai** [comment]
> do a better clean up job for multiple editors. Can you open a new tickets for this? 'Editor clean up not properly disposing of event handlers' maybe?

Sure will do
