### ISSUE TITLE
How to start file upload?

### ISSUE THREAD

**Issue by gitapteryx** [tinymce/tinymce-blazor#48]
As the title, thank you!

**Comment by gitapteryx** [comment]
> Ref: INT-2937

Thank you for your answer, because I don't know where to find int-2937 when I use TinyMCE for the first time. Is there a link? Thanks again!

**Comment by jscasca** [comment]
Hey @gitapteryx I don't think I follow what you are trying to do.

To upload images you can look into the TinyMCE docs: [https://www.tiny.cloud/docs/tinymce/6/image/](https://www.tiny.cloud/docs/tinymce/6/image/)

To add a custom configuration to the Blazor wrapper you can follow this instructions: [https://www.tiny.cloud/docs/integrations/blazor/#exampleusingjsconfsrc](https://www.tiny.cloud/docs/integrations/blazor/#exampleusingjsconfsrc)

**Comment by gitapteryx** [comment]
> Hey @gitapteryx I don't think I follow what you are trying to do.
> 
> To upload images you can look into the TinyMCE docs: https://www.tiny.cloud/docs/tinymce/6/image/
> 
> To add a custom configuration to the Blazor wrapper you can follow this instructions: https://www.tiny.cloud/docs/integrations/blazor/#exampleusingjsconfsrc

I understand how to use it. Thank you very much!
