### ISSUE TITLE
Could not find 'tinymceBlazorWrapper' in 'window'.

### ISSUE THREAD

**Issue by Thwar** [tinymce/tinymce-blazor#5]
![image](https://user-images.githubusercontent.com/11199179/109585211-6f603500-7ad9-11eb-996b-6a7ba15f1af1.png)

Having trouble getting the editor to work. I installed tinyMCE.Blazor package using Install-Package TinyMCE.Blazor on Windows. Is the nuget package not compactible with Blazor WebAssembly ?

Thanks

**Comment by tntwist** [comment]
Hi. It should work wiht Blazor WebAssembly. I created an example here :https://github.com/tntwist/tinymce-blazor/tree/blazor-wasm-sample/TinyMCE.Blazor.Sample.BlazorWasm

**Comment by jscasca** [comment]
Hey @Thwar 

Just checking if you are still having issues getting the editor working?

**Comment by Thwar** [comment]
Hi sorry I no longer have issues will close the issue. Thanks!
