### ISSUE TITLE
Unable to remove upgrade button

### ISSUE THREAD

**Issue by silentdevnull** [tinymce/tinymce-blazor#54]
Hello, 

I'm working on using tinymce for the first time in a project. 

I installed tinymce from nuget and tinymce.blazor. I did the scriptsrc in <Editor> tag to point to the javascript files that tinymce brought in from nuget.  

The issue I'm having is I can't make the lightning bolt upgrade button to go away. I'm wating to run this as a self hosted option. 

How can I make this button go away. 

Thanks,

**Comment by EkimChau** [comment]
Hello silentdevnull,

This is a new configuration option for TinyMCE 6.2, more details can be found here, including how to turn off this feature. https://www.tiny.cloud/docs/tinymce/6/editor-premium-upgrade-promotion/

Hope that helps

**Comment by silentdevnull** [comment]
Thank you for that information and fast reply @EkimChau. I was able to disable it in my configuration directory. 

Example for anyone else having this issue. 

```
private Dictionary<string, object> _editorConfiguration = new Dictionary<string, object> {
        { "promotion", false}
};
```
