### ISSUE TITLE
using Editor in EditForm

### ISSUE THREAD

**Issue by alizalevinger** [tinymce/tinymce-blazor#62]
Hi,  I was so excited to find this blazor wrapper for tinymce. How can I integrate inside of an EditForm. I'm getting the following error: **System.Exception: Editor is used inside and EditForm but field accessor: "Field" parameter is not specified.** 
at TinyMCE.Blazor.Editor.EnsureForParamWhenUsedInEditForm()
at TinyMCE.Blazor.Editor.OnParametesSet()....

**Comment by jscasca** [comment]
If you are inside an EditForm you need to specify the `Field` property. You can find an example of this in the README: https://github.com/tinymce/tinymce-blazor#enable-form-validation

This will allow the form to access the value of the component. Hope this helps!

**Comment by alizalevinger** [comment]
Thanks! I'll give it a try

**Comment by jscasca** [comment]
The `Field` property is only used by the `EditForm` to enable field validation and other form specific tricks. The data binding using `bind-Value` is to facilitate the use of the variable containing the editor value. As such you can use data binding outside of a form for other purposes but inside of a form you need to specify the `Field` property.

**Comment by proskilly** [comment]
The link  https://github.com/tinymce/tinymce-blazor#enable-form-validation  doesn't point to an example of form validation.
I'm struggling to get this to work, an example would be great.
