### ISSUE TITLE
WCAG errors

### ISSUE THREAD

**Issue by AkshayD07** [tinymce/tinymce-blazor#72]
![image](https://github.com/tinymce/tinymce-blazor/assets/39411837/a044f472-e5ae-4a71-ad50-4307a12257dd)
![image](https://github.com/tinymce/tinymce-blazor/assets/39411837/32e9ee3a-bb86-4963-b075-107b3fc91ef0)

Getting these parsing errors when ran through a WCAG testing tool . Is there a a way to tackle it ?

**Comment by TinyITAdmin** [comment]
Ref: INT-3224

**Comment by spocke** [comment]
This is more of a general TinyMCE issue than a Blazor integration issue. So closing this feel free to open a new ticket if you feel this is a bug on the https://github.com/tinymce/tinymce issue tracker. Explain then exactly what tool you are using and include the report if possible. Thanks
