### ISSUE TITLE
NuGet package outdated?

### ISSUE THREAD

**Issue by mhspelt** [tinymce/tinymce-blazor#85]
Hi, 
I ran into an issue where setting _ClassName_ would not do anything. Then I came here to see if it's a bug, and found it was fixed in August 2022 already (#53).

But the latest NuGet package (TinyMCE.Blazor) seems to be 1.0.4 from May 2022. Is it not getting built automatically and can you please provide an updated package?

**Comment by spocke** [comment]
We released a 2.0 version that should include that fix.
